apiVersion: v1
kind: Service
metadata:
  labels:
    default-app: {{ include "helm.release.name" . }}
  {{- if .Values.deployment.labels }}
    {{- toYaml .Values.deployment.labels | nindent 4 }}
  {{- end }}
  name: {{ include "helm.release.name" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.deployment.containerPort }}
  selector:
    default-app: {{ include "helm.release.name" . }}
  {{- if .Values.deployment.labels }}
    {{- toYaml .Values.deployment.labels | nindent 4 }}
  {{- end }}
